import matplotlib.pyplot as plt
import numpy as np

def read_data(filename):
    """Read data from the text file generated by C++ program"""
    n_values = []
    times = []
    
    try:
        with open(filename, 'r') as file:
            # Skip header line
            next(file)
            
            for line in file:
                line = line.strip()
                if line:
                    parts = line.split(',')
                    n_values.append(int(parts[0]))
                    times.append(float(parts[1]))
                    
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run the C++ program first to generate the data file.")
        return None, None
    
    return n_values, times

def plot_graph(n_values, times):
    """Create a time vs N graph for N-ary Search"""
    
    # Set up the figure with a white style
    plt.style.use('default')
    fig, ax = plt.subplots(figsize=(12, 8))
    
    # Set background color
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    # Plot the actual data - small dots connected by line
    ax.plot(n_values, times, '-', color='#1a73e8', linewidth=1.5, 
            marker='o', markersize=5, markerfacecolor='#1a73e8', 
            markeredgecolor='#1a73e8', label='Measured Time')
    
    # Highlight the optimal N (minimum time)
    min_time = min(times)
    min_idx = times.index(min_time)
    optimal_n = n_values[min_idx]
    ax.plot(optimal_n, min_time, 'o', color='#e63946', markersize=12, 
            markerfacecolor='#e63946', markeredgecolor='white', markeredgewidth=2,
            label=f'Optimal N = {optimal_n} ({min_time:.1f} ns)', zorder=5)
    
    # Customize the plot
    ax.set_xlabel('Value of N (number of parts)', fontsize=14, color='black', fontweight='bold')
    ax.set_ylabel('Time (nanoseconds)', fontsize=14, color='black', fontweight='bold')
    ax.set_title('N-ary Search: Time vs N', 
                 fontsize=18, color='#1a73e8', fontweight='bold', pad=20)
    
    # Add grid
    ax.grid(True, linestyle='--', alpha=0.3, color='gray')
    
    # Customize ticks
    ax.tick_params(axis='both', colors='black', labelsize=11)
    
    # Auto-scale Y-axis based on data with 10% padding
    max_time = max(times) * 1.1
    ax.set_ylim(0, max_time)
    
    # Set X-axis ticks
    ax.set_xticks(range(min(n_values), max(n_values) + 1, 2))
    
    # Add legend
    legend = ax.legend(loc='upper right', fontsize=12, facecolor='white', 
                       edgecolor='gray', labelcolor='black')
    
    # Adjust layout
    plt.tight_layout()
    
    # Save the graph
    plt.savefig('nary_search_graph.png', dpi=150, facecolor='white', 
                edgecolor='none', bbox_inches='tight')
    print("Graph saved as: nary_search_graph.png")
    
    # Show the graph
    plt.show()

def main():
    print("=" * 55)
    print("     N-ARY SEARCH - TIME vs N VISUALIZATION          ")
    print("=" * 55)
    print()
    
    # Read data from the text file
    n_values, times = read_data('nary_search_results.txt')
    
    if n_values is None or times is None:
        return
    
    # Display the data
    print("Data from C++ Program:")
    print("-" * 40)
    print(f"{'N':<15} {'Time (ns)':<15}")
    print("-" * 40)
    for n, time in zip(n_values, times):
        print(f"{n:<15} {time:<15.2f}")
    print("-" * 40)
    print()
    
    # Find optimal N
    min_time = min(times)
    min_idx = times.index(min_time)
    optimal_n = n_values[min_idx]
    
    print("Analysis:")
    print("-" * 40)
    print(f"Optimal N: {optimal_n} (fastest at {min_time:.2f} ns)")
    print(f"N=2 (Binary Search): {times[0]:.2f} ns")
    if len(times) > 1:
        print(f"N={n_values[-1]}: {times[-1]:.2f} ns")
    print("-" * 40)
    print()
    
    # Plot the graph
    print("Generating graph...")
    plot_graph(n_values, times)

if __name__ == "__main__":
    main()
