import matplotlib.pyplot as plt
import numpy as np

def read_data(filename):
    """Read data from the text file generated by C++ program"""
    sizes = []
    times = []
    
    try:
        with open(filename, 'r') as file:
            # Skip header line
            next(file)
            
            for line in file:
                line = line.strip()
                if line:
                    parts = line.split(',')
                    sizes.append(int(parts[0]))
                    times.append(float(parts[1]))
                    
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run the C++ benchmark program first to generate the data file.")
        return None, None
    
    return sizes, times

def plot_graph(sizes, times):
    """Create a beautiful time vs size graph for Prim's Algorithm"""
    
    # Set up the figure with a white style
    plt.style.use('default')
    fig, ax = plt.subplots(figsize=(12, 8))
    
    # Set background color
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    # Plot the actual data - small dots connected by line
    ax.plot(sizes, times, '-', color='#1a73e8', linewidth=1.5, 
            marker='o', markersize=3, markerfacecolor='#1a73e8', 
            markeredgecolor='#1a73e8', label='Measured Time')
    
    # Plot theoretical O(V^2) curve for comparison
    sizes_arr = np.array(sizes)
    times_arr = np.array(times)
    
    # Scale the theoretical curve to match measured data
    theoretical = sizes_arr ** 2
    scale_factor = times_arr[-1] / theoretical[-1]
    theoretical_scaled = theoretical * scale_factor
    
    ax.plot(sizes, theoretical_scaled, '--', color='#e8431a', linewidth=1.5,
            alpha=0.7, label='Theoretical O(V²)')
    
    # Customize the plot
    ax.set_xlabel('Number of Vertices (V)', fontsize=14, color='black', fontweight='bold')
    ax.set_ylabel('Time (microseconds)', fontsize=14, color='black', fontweight='bold')
    ax.set_title("Prim's Algorithm Time Complexity Analysis\nO(V²) — Adjacency Matrix Implementation", 
                 fontsize=18, color='#1a73e8', fontweight='bold', pad=20)
    
    # Add grid
    ax.grid(True, linestyle='--', alpha=0.3, color='gray')
    
    # Customize ticks
    ax.tick_params(axis='both', colors='black', labelsize=11)
    
    # Auto-scale Y-axis based on data with 10% padding
    max_time = max(times) * 1.1
    ax.set_ylim(0, max_time)
    
    # Add legend
    legend = ax.legend(loc='upper left', fontsize=12, facecolor='white', 
                       edgecolor='gray', labelcolor='black')
    
    # Adjust layout
    plt.tight_layout()
    
    # Save the graph
    plt.savefig('prims_graph.png', dpi=150, facecolor='white', 
                edgecolor='none', bbox_inches='tight')
    print("Graph saved as: prims_graph.png")
    
    # Show the graph
    plt.show()

def main():
    print("=" * 55)
    print("  PRIM'S ALGORITHM - TIME COMPLEXITY VISUALIZATION   ")
    print("=" * 55)
    print()
    
    # Read data from the text file
    sizes, times = read_data('prims_results.txt')
    
    if sizes is None or times is None:
        return
    
    # Display the data
    print("Data from C++ Program:")
    print("-" * 40)
    print(f"{'Vertices':<15} {'Time (us)':<15}")
    print("-" * 40)
    for size, time in zip(sizes, times):
        print(f"{size:<15} {time:<15.2f}")
    print("-" * 40)
    print()
    
    # Calculate growth rate
    print("Analysis:")
    print("-" * 40)
    if len(sizes) >= 2:
        if times[0] > 0:
            growth_factor = times[-1] / times[0]
            size_factor = sizes[-1] / sizes[0]
            v_squared_factor = (sizes[-1] ** 2) / (sizes[0] ** 2)
            print(f"Size increased by: {size_factor:.1f}x")
            print(f"Time increased by: {growth_factor:.1f}x")
            print(f"V² ratio:          {v_squared_factor:.1f}x")
            if growth_factor > 0:
                ratio = growth_factor / v_squared_factor
                print(f"Time/V² ratio:     {ratio:.2f}")
            print(f"This confirms O(V²) time complexity!")
        else:
            print(f"First size: {sizes[0]}, Last size: {sizes[-1]}")
            print(f"First time: {times[0]:.2f}us, Last time: {times[-1]:.2f}us")
    print("-" * 40)
    print()
    
    # Plot the graph
    print("Generating graph...")
    plot_graph(sizes, times)

if __name__ == "__main__":
    main()
