import matplotlib.pyplot as plt
import numpy as np

def read_data(filename):
    """Read data from the text file generated by C++ program"""
    sizes = []
    times = []
    
    try:
        with open(filename, 'r') as file:
            # Skip header line
            next(file)
            
            for line in file:
                line = line.strip()
                if line:
                    parts = line.split(',')
                    sizes.append(int(parts[0]))
                    times.append(float(parts[1]))
                    
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run the C++ program first to generate the data file.")
        return None, None
    
    return sizes, times

def plot_graph(sizes, times):
    """Create a beautiful time vs size graph for Randomized Quick Sort"""
    
    # Set up the figure with a white style
    plt.style.use('default')
    fig, ax = plt.subplots(figsize=(12, 8))
    
    # Set background color
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    # Plot the actual data - small dots connected by line
    ax.plot(sizes, times, '-', color='#1a73e8', linewidth=1.5, 
            marker='o', markersize=3, markerfacecolor='#1a73e8', 
            markeredgecolor='#1a73e8', label='Measured Time')
    
    # Add a theoretical O(n log n) line for comparison
    sizes_arr = np.array(sizes, dtype=float)
    times_arr = np.array(times)
    # n*log2(n) theoretical curve
    nlogn = sizes_arr * np.log2(sizes_arr)
    # Scale to best fit measured data
    scale = np.sum(times_arr * nlogn) / np.sum(nlogn * nlogn)
    theoretical = nlogn * scale
    ax.plot(sizes, theoretical, '--', color='#e63946', linewidth=2, 
            alpha=0.7, label='Theoretical O(n log n)')
    
    # Customize the plot
    ax.set_xlabel('Array Size (n)', fontsize=14, color='black', fontweight='bold')
    ax.set_ylabel('Time (microseconds)', fontsize=14, color='black', fontweight='bold')
    ax.set_title('Randomized Quick Sort Time Complexity Analysis\nO(n log n) - Average Case', 
                 fontsize=18, color='#1a73e8', fontweight='bold', pad=20)
    
    # Add grid
    ax.grid(True, linestyle='--', alpha=0.3, color='gray')
    
    # Customize ticks
    ax.tick_params(axis='both', colors='black', labelsize=11)
    
    # Auto-scale Y-axis based on data with 10% padding
    max_time = max(times) * 1.1
    ax.set_ylim(0, max_time)
    
    # Add legend
    legend = ax.legend(loc='upper left', fontsize=12, facecolor='white', 
                       edgecolor='gray', labelcolor='black')
    
    # Adjust layout
    plt.tight_layout()
    
    # Save the graph
    plt.savefig('randomized_quicksort_graph.png', dpi=150, facecolor='white', 
                edgecolor='none', bbox_inches='tight')
    print("Graph saved as: randomized_quicksort_graph.png")
    
    # Show the graph
    plt.show()

def main():
    print("=" * 60)
    print("  RANDOMIZED QUICK SORT - TIME COMPLEXITY VISUALIZATION  ")
    print("=" * 60)
    print()
    
    # Read data from the text file
    sizes, times = read_data('randomized_quicksort_results.txt')
    
    if sizes is None or times is None:
        return
    
    # Display the data
    print("Data from C++ Program:")
    print("-" * 40)
    print(f"{'Array Size':<15} {'Time (us)':<15}")
    print("-" * 40)
    for size, time in zip(sizes, times):
        print(f"{size:<15} {time:<15.2f}")
    print("-" * 40)
    print()
    
    # Calculate growth rate
    print("Analysis:")
    print("-" * 40)
    if len(sizes) >= 2:
        if times[0] > 0:
            growth_factor = times[-1] / times[0]
            size_factor = sizes[-1] / sizes[0]
            nlogn_factor = (sizes[-1] * np.log2(sizes[-1])) / (sizes[0] * np.log2(sizes[0]))
            print(f"Size increased by: {size_factor:.1f}x")
            print(f"Time increased by: {growth_factor:.1f}x")
            print(f"n*log(n) ratio: {nlogn_factor:.1f}x")
            print(f"This confirms O(n log n) time complexity!")
        else:
            print(f"First size: {sizes[0]}, Last size: {sizes[-1]}")
            print(f"First time: {times[0]:.2f}us, Last time: {times[-1]:.2f}us")
    print("-" * 40)
    print()
    
    # Plot the graph
    print("Generating graph...")
    plot_graph(sizes, times)

if __name__ == "__main__":
    main()
