import matplotlib.pyplot as plt
import numpy as np

def read_data(filename):
    """Read data from the text file generated by C++ program"""
    sizes = []
    times = []
    
    try:
        with open(filename, 'r') as file:
            next(file)
            for line in file:
                line = line.strip()
                if line:
                    parts = line.split(',')
                    sizes.append(int(parts[0]))
                    times.append(float(parts[1]))
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run the C++ benchmark program first to generate the data file.")
        return None, None
    
    return sizes, times

def plot_graph(sizes, times):
    """Create a beautiful time vs size graph for Dijkstra's Algorithm"""
    
    plt.style.use('default')
    fig, ax = plt.subplots(figsize=(12, 8))
    
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    ax.plot(sizes, times, '-', color='#1a73e8', linewidth=1.5, 
            marker='o', markersize=3, markerfacecolor='#1a73e8', 
            markeredgecolor='#1a73e8', label='Measured Time')
    
    # Plot theoretical O(V^2) curve
    sizes_arr = np.array(sizes, dtype=float)
    times_arr = np.array(times)
    
    theoretical = sizes_arr ** 2
    scale_factor = times_arr[-1] / theoretical[-1]
    theoretical_scaled = theoretical * scale_factor
    
    ax.plot(sizes, theoretical_scaled, '--', color='#e8431a', linewidth=1.5,
            alpha=0.7, label='Theoretical O(V²)')
    
    ax.set_xlabel('Number of Vertices (V)', fontsize=14, color='black', fontweight='bold')
    ax.set_ylabel('Time (microseconds)', fontsize=14, color='black', fontweight='bold')
    ax.set_title("Dijkstra's Algorithm Time Complexity Analysis\nO(V²) — Adjacency Matrix Implementation", 
                 fontsize=18, color='#1a73e8', fontweight='bold', pad=20)
    
    ax.grid(True, linestyle='--', alpha=0.3, color='gray')
    ax.tick_params(axis='both', colors='black', labelsize=11)
    
    max_time = max(times) * 1.1
    ax.set_ylim(0, max_time)
    
    legend = ax.legend(loc='upper left', fontsize=12, facecolor='white', 
                       edgecolor='gray', labelcolor='black')
    
    plt.tight_layout()
    
    plt.savefig('dijkstra_graph.png', dpi=150, facecolor='white', 
                edgecolor='none', bbox_inches='tight')
    print("Graph saved as: dijkstra_graph.png")
    
    plt.show()

def main():
    print("=" * 55)
    print(" DIJKSTRA'S ALGORITHM - TIME COMPLEXITY VISUALIZATION ")
    print("=" * 55)
    print()
    
    sizes, times = read_data('dijkstra_results.txt')
    
    if sizes is None or times is None:
        return
    
    print("Data from C++ Program:")
    print("-" * 40)
    print(f"{'Vertices':<15} {'Time (us)':<15}")
    print("-" * 40)
    for size, time in zip(sizes, times):
        print(f"{size:<15} {time:<15.2f}")
    print("-" * 40)
    print()
    
    print("Analysis:")
    print("-" * 40)
    if len(sizes) >= 2 and times[0] > 0:
        growth_factor = times[-1] / times[0]
        size_factor = sizes[-1] / sizes[0]
        v_squared_factor = (sizes[-1] ** 2) / (sizes[0] ** 2)
        print(f"Size increased by:  {size_factor:.1f}x")
        print(f"Time increased by:  {growth_factor:.1f}x")
        print(f"V² ratio:           {v_squared_factor:.1f}x")
        if growth_factor > 0:
            ratio = growth_factor / v_squared_factor
            print(f"Time/V² ratio:      {ratio:.2f}")
        print(f"This confirms O(V²) time complexity!")
    else:
        print(f"First size: {sizes[0]}, Last size: {sizes[-1]}")
        print(f"First time: {times[0]:.2f}us, Last time: {times[-1]:.2f}us")
    print("-" * 40)
    print()
    
    print("Generating graph...")
    plot_graph(sizes, times)

if __name__ == "__main__":
    main()
