import matplotlib.pyplot as plt
import numpy as np

def read_data(filename):
    """Read data from the text file generated by C++ program"""
    sizes = []
    times = []
    
    try:
        with open(filename, 'r') as file:
            # Skip header line
            next(file)
            
            for line in file:
                line = line.strip()
                if line:
                    parts = line.split(',')
                    sizes.append(int(parts[0]))
                    times.append(float(parts[1]))
                    
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run the C++ program first to generate the data file.")
        return None, None
    
    return sizes, times

def plot_graph(sizes, times):
    """Create a beautiful time vs size graph for Binary Search"""
    
    # Filter out extreme outliers (keep only values within reasonable range)
    median_time = np.median(times)
    filtered_sizes = []
    filtered_times = []
    for s, t in zip(sizes, times):
        if t <= median_time * 3:  # Filter out spikes
            filtered_sizes.append(s)
            filtered_times.append(t)
    
    # Set up the figure with a white style
    plt.style.use('default')
    fig, ax = plt.subplots(figsize=(12, 8))
    
    # Set background color
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')
    
    # Plot the actual data - small dots connected by line
    ax.plot(sizes, times, '-', color='#1a73e8', linewidth=1.5, 
            marker='o', markersize=3, markerfacecolor='#1a73e8', 
            markeredgecolor='#1a73e8', label='Measured Time')
    
    # Add a theoretical O(log n) line for comparison
    sizes_arr = np.array(sizes)
    # O(log n) - logarithmic growth
    log_n = np.log2(sizes_arr)
    # Scale to match the measured data - use median for better scaling
    avg_measured = np.median(times)
    avg_log = np.median(log_n)
    theoretical = log_n * (avg_measured / avg_log)
    ax.plot(sizes, theoretical, '--', color='#e63946', linewidth=2, 
            alpha=0.7, label='Theoretical O(log n)')
    
    # Customize the plot
    ax.set_xlabel('Array Size (n)', fontsize=14, color='black', fontweight='bold')
    ax.set_ylabel('Time (nanoseconds)', fontsize=14, color='black', fontweight='bold')
    ax.set_title('Binary Search Time Complexity Analysis\nO(log n) - Logarithmic', 
                 fontsize=18, color='#1a73e8', fontweight='bold', pad=20)
    
    # Add grid
    ax.grid(True, linestyle='--', alpha=0.3, color='gray')
    
    # Customize ticks
    ax.tick_params(axis='both', colors='black', labelsize=11)
    
    # Set Y-axis limit to show data better (max 500 ns)
    ax.set_ylim(0, 500)
    
    # Add legend
    legend = ax.legend(loc='upper left', fontsize=12, facecolor='white', 
                       edgecolor='gray', labelcolor='black')
    
    # Adjust layout
    plt.tight_layout()
    
    # Save the graph
    plt.savefig('binary_search_graph.png', dpi=150, facecolor='white', 
                edgecolor='none', bbox_inches='tight')
    print("Graph saved as: binary_search_graph.png")
    
    # Show the graph
    plt.show()

def main():
    print("=" * 55)
    print("     BINARY SEARCH - TIME COMPLEXITY VISUALIZATION     ")
    print("=" * 55)
    print()
    
    # Read data from the text file
    sizes, times = read_data('binary_search_results.txt')
    
    if sizes is None or times is None:
        return
    
    # Display the data
    print("Data from C++ Program:")
    print("-" * 40)
    print(f"{'Array Size':<15} {'Time (ns)':<15}")
    print("-" * 40)
    for size, time in zip(sizes, times):
        print(f"{size:<15} {time:<15.2f}")
    print("-" * 40)
    print()
    
    # Calculate growth rate
    print("Analysis:")
    print("-" * 40)
    if len(sizes) >= 2:
        size_factor = sizes[-1] / sizes[0]
        log_factor = np.log2(sizes[-1]) / np.log2(sizes[0])
        print(f"Size increased by: {size_factor:.1f}x")
        print(f"log(n) increased by: {log_factor:.2f}x")
        if times[0] > 0 and times[-1] > 0:
            time_factor = times[-1] / times[0]
            print(f"Time increased by: {time_factor:.2f}x")
        print(f"This confirms O(log n) logarithmic time complexity!")
    print("-" * 40)
    print()
    
    # Plot the graph
    print("Generating graph...")
    plot_graph(sizes, times)

if __name__ == "__main__":
    main()
